/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bsb

import dev.kord.core.Kord

suspend fun main() {
    val config = parse("data/bsb.yaml")
    val kord = Kord(config.discord.token)

    kord.login()
}
