/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bsb

import bsb.model.money.MoneyModel
import dev.kord.core.Kord
import dev.kord.core.behavior.interaction.response.respond
import dev.kord.core.event.interaction.ChatInputCommandInteractionCreateEvent
import dev.kord.core.on
import dev.kord.rest.builder.interaction.string

suspend fun main() {
	println(System.getProperty("user.dir"))
    val config = parse("data/bsb.yaml")
    val token = System.getenv("BSB_TOKEN") ?: config.getOrThrow().discord.token
    val kord = Kord(token)

    val sarcasmCmd = kord.createGlobalChatInputCommand(
        "sarcasm",
        "Make your text sarcastic"
    ) {
        string("text", "text to WrItE lIkE tHiS") {
            required = true
        }
    }

    kord.on<ChatInputCommandInteractionCreateEvent> {
        if (this.interaction.command.rootId != sarcasmCmd.id) {
			return@on
		}
		val response = interaction.deferPublicResponse()
        val command = interaction.command
        val text = command.strings["text"]!!
        val newtext = text.mapIndexed { idx, value -> if (idx % 2 == 0) value else value.uppercaseChar() }.toCharArray()
        response.respond { content = String(newtext) }
    }

    val mm = MoneyModel(kord)

    kord.login()
}